name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install gtk3
      run: sudo apt-get install -y libgtk-3-dev

    - name: Build library
      run: cd build/gmake_linux && make
    - name: Expose static library
      uses: actions/upload-artifact@v3
      with:
        name: static-lib
        path: |
          build/lib
